In [2]:
from pathlib import Path

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [3]:
DATA_PATH = Path("../data/assurance-maladie.csv")

df = pd.read_csv(DATA_PATH)

df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
df.duplicated().sum()

np.int64(1)

In [6]:
df = df.drop_duplicates()

df.shape

(1337, 7)

In [7]:
X = df.drop("charges", axis=1)
y = df["charges"]

In [8]:
X.head()

   age     sex     bmi  children smoker     region
0   19  female  27.900         0    yes  southwest
1   18    male  33.770         1     no  southeast
2   28    male  33.000         3     no  southeast
3   33    male  22.705         0     no  northwest
4   32    male  28.880         0     no  northwest

In [9]:
y.head()

0    16884.92400
1     1725.55230
2     4449.46200
3    21984.47061
4     3866.85520
Name: charges, dtype: float64

In [10]:
numeric_features = ["age", "bmi", "children"]
categorical_features = ["sex", "smoker", "region"]

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [12]:
numeric_transformer = Pipeline(
    steps=[
        ("scaler", StandardScaler())
    ]
)

categorical_transformer = Pipeline(
    steps=[
        ("encoder", OneHotEncoder(handle_unknown="ignore"))
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)

In [13]:
X_train_processed = preprocessor.fit_transform(X_train)

X_test_processed = preprocessor.transform(X_test)

In [14]:
X_train_processed.shape

(1069, 11)

In [15]:
encoded_feature_names = preprocessor.get_feature_names_out()

encoded_feature_names

array(['num__age', 'num__bmi', 'num__children', 'cat__sex_female',
       'cat__sex_male', 'cat__smoker_no', 'cat__smoker_yes',
       'cat__region_northeast', 'cat__region_northwest',
       'cat__region_southeast', 'cat__region_southwest'], dtype=object)

In [16]:
import pandas as pd

X_train_processed_df = pd.DataFrame(
    X_train_processed,
    columns=encoded_feature_names
)

X_train_processed_df.head()

,num__age,num__bmi,num__children,cat__sex_female,cat__sex_male,cat__smoker_no,cat__smoker_yes,cat__region_northeast,cat__region_northwest,cat__region_southeast,cat__region_southwest
0,-1.157680,-0.996928,-0.907908,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0
1,-1.300619,-0.792762,0.766904,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0
2,0.914926,1.154664,0.766904,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
3,1.701087,1.806837,-0.907908,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
4,0.557580,-0.651417,0.766904,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0